// Structured curriculum data for GyaanSetu.
// Chapter titles follow the official NCERT/CBSE syllabus structure to the best of
// available public knowledge. Content is original educational notes (not verbatim
// textbook reproduction) created from the official syllabus. Admin can extend/edit.
//
// Source/version note: NCERT academic session 2024–25 syllabus structure.
// UKG uses an age-appropriate foundational structure (not a formal board syllabus).

export interface CurriculumChapter {
  no: number;
  title: string;
}
export interface CurriculumSubject {
  name: string;
  slug: string;
  chapters: CurriculumChapter[];
}
export interface CurriculumClass {
  name: string;
  slug: string;
  description?: string;
  subjects: CurriculumSubject[];
}

const S = (name: string, slug: string, chapters: [string, number?][]): CurriculumSubject => ({
  name,
  slug,
  chapters: chapters.map(([title, no], i) => ({ title, no: no ?? i + 1 })),
});

export const CURRICULUM: CurriculumClass[] = [
  {
    name: "UKG",
    slug: "ukg",
    description: "Foundational pre-primary stage — age-appropriate early learning.",
    subjects: [
      S("English (Foundational)", "english-foundational", [
        ["Alphabet Fun A–Z", 1],
        ["Phonics and Sounds", 2],
        ["Sight Words", 3],
        ["Picture Reading", 4],
        ["Rhymes and Stories", 5],
        ["Simple Sentences", 6],
      ]),
      S("Hindi (Foundational)", "hindi-foundational", [
        ["स्वर परिचय (Vowels)", 1],
        ["व्यंजन परिचय (Consonants)", 2],
        ["मात्राएँ (Matras)", 3],
        ["चित्र वाचन (Picture Reading)", 4],
        ["कहानी और कविता", 5],
        ["शब्द पहचान", 6],
      ]),
      S("Mathematics (Foundational)", "mathematics-foundational", [
        ["Pre-Number Concepts", 1],
        ["Numbers 1 to 10", 2],
        ["Shapes Around Us", 3],
        ["Big and Small", 4],
        ["Patterns", 5],
        ["Measurement — Long and Short", 6],
      ]),
      S("General Awareness / EVS", "general-awareness-evs", [
        ["My Family", 1],
        ["My School", 2],
        ["Plants and Animals", 3],
        ["Seasons", 4],
        ["Good Habits", 5],
        ["My Body", 6],
      ]),
    ],
  },
  {
    name: "Class 1",
    slug: "class-1",
    subjects: [
      S("English", "english", [
        ["A Happy Child", 1],
        ["Three Little Pigs", 2],
        ["The Bubble, the Straw and the Shoe", 3],
        ["One and Many", 4],
        ["Who am I?", 5],
        ["The Pumpkin Story", 6],
        ["Fun with Numbers", 7],
      ]),
      S("Hindi", "hindi", [
        ["झूला", 1],
        ["आम की कहानी", 2],
        ["आम की टोकरी", 3],
        ["पत्ते ही पत्ते", 4],
        ["पकौड़ी", 5],
        ["छुक-छुक गाड़ी", 6],
        ["चिड़िया की बच्ची", 7],
      ]),
      S("Mathematics", "mathematics", [
        ["Shapes and Space", 1],
        ["Numbers 1 to 9", 2],
        ["Addition", 3],
        ["Subtraction", 4],
        ["Numbers 10 to 20", 5],
        ["Time", 6],
        ["Measurement", 7],
        ["Numbers 21 to 50", 8],
        ["Data Handling", 9],
        ["Patterns", 10],
        ["How Many?", 11],
      ]),
      S("EVS (Environmental Studies)", "evs", [
        ["Family and Friends", 1],
        ["Food", 2],
        ["Shelter", 3],
        ["Water", 4],
        ["Clothes", 5],
        ["Travel", 6],
        ["Things We Make and Do", 7],
      ]),
    ],
  },
  {
    name: "Class 2",
    slug: "class-2",
    subjects: [
      S("English", "english", [
        ["First Day at School", 1],
        ["The Giving Seed", 2],
        ["The Word Fun", 3],
        ["The Mogli's Family", 4],
        ["My Neighbourhood", 5],
        ["What a Bird Told Me", 6],
      ]),
      S("Hindi", "hindi", [
        ["पाठ 1 — ऊँट चला", 1],
        ["पाठ 2 — भालू ने खेली फुटबॉल", 2],
        ["पाठ 3 — म्याऊँ, म्याऊँ!!", 3],
        ["पाठ 4 — अधिक बलवान कौन?", 4],
        ["पाठ 5 — दोस्त की मदद", 5],
        ["पाठ 6 — बहादुर बेटा", 6],
      ]),
      S("Mathematics", "mathematics", [
        ["What is Long, What is Round?", 1],
        ["Counting in Groups", 2],
        ["How Much Can You Carry?", 3],
        ["Counting in Tens", 4],
        ["Patterns", 5],
        ["Footprints", 6],
        ["Jugs and Mugs", 7],
        ["Tens and Ones", 8],
        ["My Funday", 9],
        ["Add Our Points", 10],
        ["Lines and Lines", 11],
        ["Give and Take", 12],
      ]),
      S("EVS (Environmental Studies)", "evs", [
        ["The Plant Fairy", 1],
        ["The Miracle of Nature", 2],
        ["Animals and Us", 3],
        ["Food We Eat", 4],
        ["Water, Water, Everywhere", 5],
        ["Our Houses", 6],
        ["Transport and Communication", 7],
      ]),
    ],
  },
  {
    name: "Class 3",
    slug: "class-3",
    subjects: [
      S("English", "english", [
        ["The Magic Garden", 1],
        ["The Tiny Teacher", 2],
        ["The Yellow Butterfly", 3],
        ["The Story of the Road", 4],
        ["Little Tiger, Big Tiger", 5],
        ["The Balloon Man", 6],
      ]),
      S("Hindi", "hindi", [
        ["पाठ 1 — कंचा", 1],
        ["पाठ 2 — पेड़ों पर चढ़ना", 2],
        ["पाठ 3 — बाज और साँप", 3],
        ["पाठ 4 — चार चीज़ें", 4],
        ["पाठ 5 — फ़ूल", 5],
        ["पाठ 6 — तितली", 6],
      ]),
      S("Mathematics", "mathematics", [
        ["Where to Look From", 1],
        ["Fun with Numbers", 2],
        ["Give and Take", 3],
        ["Long and Short", 4],
        ["Shapes and Designs", 5],
        ["Fun with Give and Take", 6],
        ["Time Goes On", 7],
        ["Who is Heavier?", 8],
        ["How Many Times?", 9],
        ["Play with Patterns", 10],
        ["Jugs and Mugs", 11],
        ["Can We Share?", 12],
        ["Smart Charts", 13],
        ["Rupees and Paise", 14],
      ]),
      S("EVS (Environmental Studies)", "evs", [
        ["Poonam's Day Out", 1],
        ["The Plant Fairy", 2],
        ["Water Friends", 3],
        ["Our First School", 4],
        ["Chhotu's House", 5],
        ["Foods We Eat", 6],
        ["Saying without Speaking", 7],
        ["Flying High", 8],
        ["From Here to There", 9],
        ["Work We Do", 10],
      ]),
    ],
  },
  {
    name: "Class 4",
    slug: "class-4",
    subjects: [
      S("English", "english", [
        ["Wake Up!", 1],
        ["Neha's Alarm Clock", 2],
        ["The Little Fir Tree", 3],
        ["The Scholar's Mother Tongue", 4],
        ["The Green Weaver", 5],
        ["The Story of the Tenth Guru", 6],
      ]),
      S("Hindi", "hindi", [
        ["पाठ 1 — मन मोर", 1],
        ["पाठ 2 — सुनीता की पहिया कुर्सी", 2],
        ["पाठ 3 — मज़ा आया", 3],
        ["पाठ 4 — नादान दोस्त", 4],
        ["पाठ 5 — अक्ल बड़ी या भैंस", 5],
        ["पाठ 6 — भूल", 6],
      ]),
      S("Mathematics", "mathematics", [
        ["Building with Bricks", 1],
        ["Long and Short", 2],
        ["A Trip to Bhopal", 3],
        ["Tick-Tick-Tick", 4],
        ["The Way The World Looks", 5],
        ["The Junk Seller", 6],
        ["Jugs and Mugs", 7],
        ["Carts and Wheels", 8],
        ["Halves and Quarters", 9],
        ["Play with Patterns", 10],
        ["Tables and Shares", 11],
        ["How Heavy? How Light?", 12],
        ["Fields and Fences", 13],
        ["Smart Charts", 14],
      ]),
      S("EVS (Environmental Studies)", "evs", [
        ["Going to School", 1],
        ["Ear to Ear", 2],
        ["The Story of Amrita", 3],
        ["Anita and the Honeybees", 4],
        ["Omana's Journey", 5],
        ["From the Window", 6],
        ["Reaching Grandmother's House", 7],
        ["Every Drop Counts", 8],
        ["Food and Fun", 9],
        ["Hu Tu Tu, Hu Tu Tu", 10],
      ]),
    ],
  },
  {
    name: "Class 5",
    slug: "class-5",
    subjects: [
      S("English", "english", [
        ["Ice-cream Man", 1],
        ["Wonderful Waste!", 2],
        ["Grandma's Tree", 3],
        ["The Talkative Barber", 4],
        ["The Little Bully", 5],
        ["The Boastful Turtle", 6],
      ]),
      S("Hindi", "hindi", [
        ["पाठ 1 — राख की रस्सी", 1],
        ["पाठ 2 — फ़सलों के त्योहार", 2],
        ["पाठ 3 — खिलौनेवाला", 3],
        ["पाठ 4 — नन्हा फ़नूस", 4],
        ["पाठ 5 — झांसी की रानी", 5],
        ["पाठ 6 — जो देखकर भी हम नहीं देखते", 6],
      ]),
      S("Mathematics", "mathematics", [
        ["The Fish Tale", 1],
        ["Shapes and Angles", 2],
        ["How Many Squares?", 3],
        ["Parts and Wholes", 4],
        ["Does it Look the Same?", 5],
        ["Be My Multiple, I'll be Your Factor", 6],
        ["Can You See the Pattern?", 7],
        ["Mapping Your Way", 8],
        ["Boxes and Sketches", 9],
        ["Tenths and Hundredths", 10],
        ["Area and its Boundary", 11],
        ["Smart Charts", 12],
        ["Ways to Multiply and Divide", 13],
        ["How Big? How Heavy?", 14],
      ]),
      S("EVS (Environmental Studies)", "evs", [
        ["Super Senses", 1],
        ["A Snake Charmer's Story", 2],
        ["From Tasting to Digesting", 3],
        ["Mangoes Round the Year", 4],
        ["Seeds and Seeds", 5],
        ["Every Drop Counts", 6],
        ["Experiments with Water", 7],
        ["A Treat for Mosquitoes", 8],
        ["Up You Go!", 9],
        ["Walls Tell Stories", 10],
        ["Sunita in Space", 11],
      ]),
    ],
  },
  {
    name: "Class 6",
    slug: "class-6",
    subjects: [
      S("English", "english", [
        ["Who Did Patrick's Homework?", 1],
        ["How the Dog Found Himself a New Master!", 2],
        ["Taro's Reward", 3],
        ["An Indian — American Woman in Space", 4],
        ["A Different Kind of School", 5],
        ["Who I Am", 6],
        ["Fair Play", 7],
        ["A Game of Chance", 8],
        ["Desert Animals", 9],
        ["The Banyan Tree", 10],
      ]),
      S("Hindi", "hindi", [
        ["पाठ 1 — वह चिड़िया जो", 1],
        ["पाठ 2 — बचपन", 2],
        ["पाठ 3 — नादान दोस्त", 3],
        ["पाठ 4 — चाँद से थोड़ी दूर", 4],
        ["पाठ 5 — अक्ल बड़ी या भैंस", 5],
        ["पाठ 6 — पर्वत परदेशी", 6],
        ["पाठ 7 — साथी हाथ बढ़ाना", 7],
      ]),
      S("Mathematics", "mathematics", [
        ["Knowing Our Numbers", 1],
        ["Whole Numbers", 2],
        ["Playing with Numbers", 3],
        ["Basic Geometrical Ideas", 4],
        ["Understanding Elementary Shapes", 5],
        ["Integers", 6],
        ["Fractions", 7],
        ["Decimals", 8],
        ["Data Handling", 9],
        ["Mensuration", 10],
        ["Algebra", 11],
        ["Ratio and Proportion", 12],
        ["Symmetry", 13],
        ["Practical Geometry", 14],
      ]),
      S("Science", "science", [
        ["Food: Where Does It Come From?", 1],
        ["Components of Food", 2],
        ["Fibre to Fabric", 3],
        ["Sorting Materials into Groups", 4],
        ["Separation of Substances", 5],
        ["Changes Around Us", 6],
        ["Getting to Know Plants", 7],
        ["Body Movements", 8],
        ["The Living Organisms and Their Surroundings", 9],
        ["Motion and Measurement of Distances", 10],
        ["Light, Shadows and Reflections", 11],
        ["Electricity and Circuits", 12],
        ["Fun with Magnets", 13],
        ["Water", 14],
        ["Air Around Us", 15],
        ["Garbage In, Garbage Out", 16],
      ]),
      S("Social Science", "social-science", [
        ["What, Where, How and When?", 1],
        ["From Hunting–Gathering to Growing Food", 2],
        ["In the Earliest Cities", 3],
        ["What Books and Burials Tell Us", 4],
        ["Kingdoms, Kings and an Early Republic", 5],
        ["New Empires and Kingdoms", 6],
        ["The Earth in the Solar System", 7],
        ["Globe: Latitudes and Longitudes", 8],
        ["Motions of the Earth", 9],
        ["Maps", 10],
        ["Major Domains of the Earth", 11],
        ["Our Country — India", 12],
        ["Understanding Diversity", 13],
        ["Diversity and Discrimination", 14],
        ["What is Government?", 15],
        ["Panjayat Raj", 16],
      ]),
      S("Sanskrit", "sanskrit", [
        ["शब्द परिचयः 1", 1],
        ["शब्द परिचयः 2", 2],
        ["शब्द परिचयः 3", 3],
        ["विद्यालयः", 4],
        ["वृक्षाः", 5],
        ["समुद्रतटः", 6],
      ]),
    ],
  },
  {
    name: "Class 7",
    slug: "class-7",
    subjects: [
      S("English", "english", [
        ["Three Questions", 1],
        ["A Gift of Chappals", 2],
        ["Gopal and the Hilsa Fish", 3],
        ["The Ashes That Made Trees Bloom", 4],
        ["Quality", 5],
        ["Expert Detectives", 6],
        ["The Invention of Vita-Wonk", 7],
        ["Fire: Friend and Foe", 8],
        ["A Bicycle in Good Repair", 9],
        ["The Story of Cricket", 10],
      ]),
      S("Hindi", "hindi", [
        ["पाठ 1 — हम पंछी उन्मुक्त गगन का", 1],
        ["पाठ 2 — दादी माँ", 2],
        ["पाठ 3 — हिमालय की बेटियाँ", 3],
        ["पाठ 4 — कठपुतली", 4],
        ["पाठ 5 — मीठाईवाला", 5],
        ["पाठ 6 — रक्त और हमारा शरीर", 6],
      ]),
      S("Mathematics", "mathematics", [
        ["Integers", 1],
        ["Fractions and Decimals", 2],
        ["Data Handling", 3],
        ["Simple Equations", 4],
        ["Lines and Angles", 5],
        ["The Triangle and its Properties", 6],
        ["Congruence of Triangles", 7],
        ["Comparing Quantities", 8],
        ["Rational Numbers", 9],
        ["Practical Geometry", 10],
        ["Perimeter and Area", 11],
        ["Algebraic Expressions", 12],
        ["Exponents and Powers", 13],
        ["Symmetry", 14],
        ["Visualising Solid Shapes", 15],
      ]),
      S("Science", "science", [
        ["Nutrition in Plants", 1],
        ["Nutrition in Animals", 2],
        ["Fibre to Fabric", 3],
        ["Heat", 4],
        ["Acids, Bases and Salts", 5],
        ["Physical and Chemical Changes", 6],
        ["Weather, Climate and Adaptations", 7],
        ["Winds, Storms and Cyclones", 8],
        ["Soil", 9],
        ["Respiration in Organisms", 10],
        ["Transportation in Animals and Plants", 11],
        ["Reproduction in Plants", 12],
        ["Motion and Time", 13],
        ["Electric Current and its Effects", 14],
        ["Light", 15],
        ["Water: A Precious Resource", 16],
        ["Forests: Our Lifeline", 17],
        ["Wastewater Story", 18],
      ]),
      S("Social Science", "social-science", [
        ["Tracing Changes Through a Thousand Years", 1],
        ["New Kings and Kingdoms", 2],
        ["The Delhi Sultans", 3],
        ["The Mughal Empire", 4],
        ["Rulers and Buildings", 5],
        ["Towns, Traders and Craftspersons", 6],
        ["Tribes, Nomads and Settled Communities", 7],
        ["Devotional Paths to the Divine", 8],
        ["The Making of Regional Cultures", 9],
        ["Eighteenth-Century Political Formations", 10],
        ["Environment", 11],
        ["Inside Our Earth", 12],
        ["Our Changing Earth", 13],
        ["Air", 14],
        ["Water", 15],
        ["Natural Vegetation and Wildlife", 16],
        ["Human Environment", 17],
        ["Human-Environment Interactions", 18],
      ]),
      S("Sanskrit", "sanskrit", [
        ["सुभाषितानि", 1],
        ["दुर्बुद्धिः विनश्यति", 2],
        ["स्वावलम्बनम्", 3],
        ["हास्यबालकविसम्मेलनम्", 4],
        ["पण्डिता रमाबाई", 5],
        ["सदाचारः", 6],
      ]),
    ],
  },
  {
    name: "Class 8",
    slug: "class-8",
    subjects: [
      S("English", "english", [
        ["The Best Christmas Present in the World", 1],
        ["The Tsunami", 2],
        ["Glimpses of the Past", 3],
        ["Bepin Choudhury's Lapse of Memory", 4],
        ["The Summit Within", 5],
        ["This is Jody's Fawn", 6],
        ["A Visit to Cambridge", 7],
        ["A Short Monsoon Diary", 8],
        ["The Great Stone Face–I", 9],
        ["The Great Stone Face–II", 10],
      ]),
      S("Hindi", "hindi", [
        ["पाठ 1 — ध्वनि", 1],
        ["पाठ 2 — लाख की चूड़ियाँ", 2],
        ["पाठ 3 — बस की यात्रा", 3],
        ["पाठ 4 — दीवानों की हस्ती", 4],
        ["पाठ 5 — चिट्ठी का सफ़र", 5],
        ["पाठ 6 — भगवान के डाकिए", 6],
      ]),
      S("Mathematics", "mathematics", [
        ["Rational Numbers", 1],
        ["Linear Equations in One Variable", 2],
        ["Understanding Quadrilaterals", 3],
        ["Practical Geometry", 4],
        ["Data Handling", 5],
        ["Squares and Square Roots", 6],
        ["Cubes and Cube Roots", 7],
        ["Comparing Quantities", 8],
        ["Algebraic Expressions and Identities", 9],
        ["Visualising Solid Shapes", 10],
        ["Mensuration", 11],
        ["Exponents and Powers", 12],
        ["Direct and Inverse Proportions", 13],
        ["Factorisation", 14],
        ["Introduction to Graphs", 15],
        ["Playing with Numbers", 16],
      ]),
      S("Science", "science", [
        ["Crop Production and Management", 1],
        ["Microorganisms: Friend and Foe", 2],
        ["Synthetic Fibres and Plastics", 3],
        ["Materials: Metals and Non-Metals", 4],
        ["Coal and Petroleum", 5],
        ["Combustion and Flame", 6],
        ["Conservation of Plants and Animals", 7],
        ["Cell — Structure and Functions", 8],
        ["Reproduction in Animals", 9],
        ["Reaching the Age of Adolescence", 10],
        ["Force and Pressure", 11],
        ["Friction", 12],
        ["Sound", 13],
        ["Chemical Effects of Electric Current", 14],
        ["Some Natural Phenomena", 15],
        ["Light", 16],
        ["Stars and the Solar System", 17],
        ["Pollution of Air and Water", 18],
      ]),
      S("Social Science", "social-science", [
        ["How, When and Where", 1],
        ["From Trade to Territory", 2],
        ["Ruling the Countryside", 3],
        ["Tribals, Dikus and the Vision of a Golden Age", 4],
        ["When People Rebel", 5],
        ["Colonialism and the City", 6],
        ["Weavers, Iron Smelters and Factory Owners", 7],
        ["Civilising the Native, Educating the Nation", 8],
        ["The Making of the National Movement", 9],
        ["India after Independence", 10],
        ["Resources", 11],
        ["Land, Soil, Water, Natural Vegetation and Wildlife", 12],
        ["Mineral and Power Resources", 13],
        ["Agriculture", 14],
        ["Industries", 15],
        ["Human Resources", 16],
      ]),
      S("Sanskrit", "sanskrit", [
        ["सुभाषितानि", 1],
        ["बिलस्य वाणी न कदापि मे श्रुता", 2],
        ["भगवद्ज्जुकम्", 3],
        ["सदैव पुरतो निधेहि चरणम्", 4],
        ["धर्मे धमनं पापे पुण्यम्", 5],
        ["प्रेमलस्य प्रेम", 6],
      ]),
    ],
  },
  {
    name: "Class 9",
    slug: "class-9",
    subjects: [
      S("English", "english", [
        ["The Fun They Had", 1],
        ["The Sound of Music", 2],
        ["The Little Girl", 3],
        ["A Truly Beautiful Mind", 4],
        ["The Snake and the Mirror", 5],
        ["My Childhood", 6],
        ["Reach for the Top", 7],
        ["A House Is Not a Home", 8],
        ["The Bond of Love", 9],
        ["Kathmandu", 10],
      ]),
      S("Hindi", "hindi", [
        ["पाठ 1 — दो बैलों की कथा", 1],
        ["पाठ 2 — ल्हासा की ओर", 2],
        ["पाठ 3 — उपभोक्तावाद की संस्कृति", 3],
        ["पाठ 4 — साँवले सपनों की याद", 4],
        ["पाठ 5 — प्रेमचंद के फटे जूते", 5],
        ["पाठ 6 — मेरे बचपन के दिन", 6],
      ]),
      S("Mathematics", "mathematics", [
        ["Number Systems", 1],
        ["Polynomials", 2],
        ["Coordinate Geometry", 3],
        ["Linear Equations in Two Variables", 4],
        ["Introduction to Euclid's Geometry", 5],
        ["Lines and Angles", 6],
        ["Triangles", 7],
        ["Quadrilaterals", 8],
        ["Areas of Parallelograms and Triangles", 9],
        ["Circles", 10],
        ["Constructions", 11],
        ["Heron's Formula", 12],
        ["Surface Areas and Volumes", 13],
        ["Statistics", 14],
        ["Probability", 15],
      ]),
      S("Science", "science", [
        ["Matter in Our Surroundings", 1],
        ["Is Matter Around Us Pure?", 2],
        ["Atoms and Molecules", 3],
        ["Structure of the Atom", 4],
        ["The Fundamental Unit of Life", 5],
        ["Tissues", 6],
        ["Diversity in Living Organisms", 7],
        ["Motion", 8],
        ["Force and Laws of Motion", 9],
        ["Gravitation", 10],
        ["Work and Energy", 11],
        ["Sound", 12],
        ["Why Do We Fall Ill?", 13],
        ["Natural Resources", 14],
        ["Improvement in Food Resources", 15],
      ]),
      S("Social Science", "social-science", [
        ["The French Revolution", 1],
        ["Socialism in Europe and the Russian Revolution", 2],
        ["Nazism and the Rise of Hitler", 3],
        ["Forest Society and Colonialism", 4],
        ["Pastoralists in the Modern World", 5],
        ["India — Size and Location", 6],
        ["Physical Features of India", 7],
        ["Drainage", 8],
        ["Climate", 9],
        ["Natural Vegetation and Wildlife", 10],
        ["Population", 11],
        ["What is Democracy? Why Democracy?", 12],
        ["Constitutional Design", 13],
        ["Electoral Politics", 14],
        ["Working of Institutions", 15],
      ]),
      S("Sanskrit", "sanskrit", [
        ["भारतवर्षम्", 1],
        ["स्वर्णकाकः", 2],
        ["गच्छति", 3],
        ["कल्पतरुः", 4],
        ["सुधामन्थनम्", 5],
        ["पर्यावरणम्", 6],
      ]),
    ],
  },
  {
    name: "Class 10",
    slug: "class-10",
    subjects: [
      S("English", "english", [
        ["A Letter to God", 1],
        ["Nelson Mandela — Long Walk to Freedom", 2],
        ["Two Stories about Flying", 3],
        ["From the Diary of Anne Frank", 4],
        ["The Hundred Dresses–I", 5],
        ["The Hundred Dresses–II", 6],
        ["Glimpses of India", 7],
        ["Mijbil the Otter", 8],
        ["Madam Rides the Bus", 9],
        ["The Sermon at Benares", 10],
        ["The Proposal", 11],
      ]),
      S("Hindi", "hindi", [
        ["पाठ 1 — सूरदास के पद", 1],
        ["पाठ 2 — राम-लक्ष्मण-परशुराम संवाद", 2],
        ["पाठ 3 — सवैये", 3],
        ["पाठ 4 — आत्मकथ्य", 4],
        ["पाठ 5 — उत्साह", 5],
        ["पाठ 6 — यह दंतुरहित मुस्कान", 6],
      ]),
      S("Mathematics", "mathematics", [
        ["Real Numbers", 1],
        ["Polynomials", 2],
        ["Pair of Linear Equations in Two Variables", 3],
        ["Quadratic Equations", 4],
        ["Arithmetic Progressions", 5],
        ["Triangles", 6],
        ["Coordinate Geometry", 7],
        ["Introduction to Trigonometry", 8],
        ["Some Applications of Trigonometry", 9],
        ["Circles", 10],
        ["Areas Related to Circles", 11],
        ["Surface Areas and Volumes", 12],
        ["Statistics", 13],
        ["Probability", 14],
      ]),
      S("Science", "science", [
        ["Chemical Reactions and Equations", 1],
        ["Acids, Bases and Salts", 2],
        ["Metals and Non-metals", 3],
        ["Carbon and its Compounds", 4],
        ["Periodic Classification of Elements", 5],
        ["Life Processes", 6],
        ["Control and Coordination", 7],
        ["How do Organisms Reproduce?", 8],
        ["Heredity and Evolution", 9],
        ["Light – Reflection and Refraction", 10],
        ["The Human Eye and the Colourful World", 11],
        ["Electricity", 12],
        ["Magnetic Effects of Electric Current", 13],
        ["Sources of Energy", 14],
        ["Our Environment", 15],
        ["Management of Natural Resources", 16],
      ]),
      S("Social Science", "social-science", [
        ["The Rise of Nationalism in Europe", 1],
        ["Nationalism in India", 2],
        ["The Making of a Global World", 3],
        ["The Age of Industrialisation", 4],
        ["Print Culture and the Modern World", 5],
        ["Resources and Development", 6],
        ["Forest and Wildlife Resources", 7],
        ["Water Resources", 8],
        ["Agriculture", 9],
        ["Minerals and Energy Resources", 10],
        ["Manufacturing Industries", 11],
        ["Lifelines of National Economy", 12],
        ["Power Sharing", 13],
        ["Federalism", 14],
        ["Democracy and Diversity", 15],
        ["Gender, Religion and Caste", 16],
      ]),
      S("Sanskrit", "sanskrit", [
        ["शुचिपर्यावरणम्", 1],
        ["बुद्धिर्बलवती सदा", 2],
        ["व्यायोगः", 3],
        ["हितोपदेशः", 4],
        ["सूक्तयः", 5],
        ["भूमन्डलरूपरेखा", 6],
      ]),
    ],
  },
  {
    name: "Class 11",
    slug: "class-11",
    subjects: [
      S("English Core", "english-core", [
        ["The Portrait of a Lady", 1],
        ["We're Not Afraid to Die", 2],
        ["Discovering Tut: The Saga Continues", 3],
        ["Landscape of the Soul", 4],
        ["The Ailing Planet", 5],
        ["The Browning Version", 6],
        ["The Adventure", 7],
        ["Silk Road", 8],
      ]),
      S("Mathematics", "mathematics", [
        ["Sets", 1],
        ["Relations and Functions", 2],
        ["Trigonometric Functions", 3],
        ["Principle of Mathematical Induction", 4],
        ["Complex Numbers", 5],
        ["Linear Inequalities", 6],
        ["Permutations and Combinations", 7],
        ["Binomial Theorem", 8],
        ["Sequences and Series", 9],
        ["Straight Lines", 10],
        ["Conic Sections", 11],
        ["Introduction to Three Dimensional Geometry", 12],
        ["Limits and Derivatives", 13],
        ["Mathematical Reasoning", 14],
        ["Statistics", 15],
        ["Probability", 16],
      ]),
      S("Physics", "physics", [
        ["Physical World", 1],
        ["Units and Measurements", 2],
        ["Motion in a Straight Line", 3],
        ["Motion in a Plane", 4],
        ["Laws of Motion", 5],
        ["Work, Energy and Power", 6],
        ["System of Particles and Rotational Motion", 7],
        ["Gravitation", 8],
        ["Mechanical Properties of Solids", 9],
        ["Mechanical Properties of Fluids", 10],
        ["Thermal Properties of Matter", 11],
        ["Thermodynamics", 12],
        ["Kinetic Theory", 13],
        ["Oscillations", 14],
        ["Waves", 15],
      ]),
      S("Chemistry", "chemistry", [
        ["Some Basic Concepts of Chemistry", 1],
        ["Structure of Atom", 2],
        ["Classification of Elements and Periodicity", 3],
        ["Chemical Bonding and Molecular Structure", 4],
        ["States of Matter", 5],
        ["Thermodynamics", 6],
        ["Equilibrium", 7],
        ["Redox Reactions", 8],
        ["Hydrogen", 9],
        ["The s-Block Elements", 10],
        ["The p-Block Elements", 11],
        ["Organic Chemistry — Basic Principles", 12],
        ["Hydrocarbons", 13],
        ["Environmental Chemistry", 14],
      ]),
      S("Biology", "biology", [
        ["The Living World", 1],
        ["Biological Classification", 2],
        ["Plant Kingdom", 3],
        ["Animal Kingdom", 4],
        ["Morphology of Flowering Plants", 5],
        ["Anatomy of Flowering Plants", 6],
        ["Structural Organisation in Animals", 7],
        ["Cell — The Unit of Life", 8],
        ["Biomolecules", 9],
        ["Cell Cycle and Cell Division", 10],
        ["Transport in Plants", 11],
        ["Mineral Nutrition", 12],
        ["Photosynthesis", 13],
        ["Respiration in Plants", 14],
        ["Plant Growth and Development", 15],
      ]),
      S("Computer Science", "computer-science", [
        ["Computer Systems", 1],
        ["Encoding Schemes and Number System", 2],
        ["Emerging Trends", 3],
        ["Introduction to Problem Solving", 4],
        ["Getting Started with Python", 5],
        ["Operators and Expressions", 6],
        ["Functions", 7],
        ["Lists, Tuples and Dictionaries", 8],
        ["Flow of Control", 9],
        ["Strings", 10],
      ]),
      S("Accountancy", "accountancy", [
        ["Introduction to Accounting", 1],
        ["Theory Base of Accounting", 2],
        ["Recording of Transactions", 3],
        ["Bank Reconciliation Statement", 4],
        ["Trial Balance", 5],
        ["Depreciation", 6],
        ["Financial Statements", 7],
        ["Accounts from Incomplete Records", 8],
      ]),
      S("Business Studies", "business-studies", [
        ["Nature and Purpose of Business", 1],
        ["Forms of Business Organisation", 2],
        ["Private, Public and Global Enterprises", 3],
        ["Business Services", 4],
        ["Emerging Modes of Business", 5],
        ["Social Responsibilities of Business", 6],
        ["Formation of a Company", 7],
        ["Sources of Business Finance", 8],
      ]),
      S("Economics", "economics", [
        ["Indian Economy on the Eve of Independence", 1],
        ["Indian Economy (1950–1990)", 2],
        ["Liberalisation, Privatisation and Globalisation", 3],
        ["Poverty", 4],
        ["Human Capital Formation", 5],
        ["Rural Development", 6],
        ["Employment", 7],
        ["Infrastructure", 8],
        ["Environment and Sustainable Development", 9],
        ["Comparative Development", 10],
      ]),
      S("Political Science", "political-science", [
        ["Constitution: Why and How?", 1],
        ["Rights in the Indian Constitution", 2],
        ["Election and Representation", 3],
        ["Executive", 4],
        ["Legislature", 5],
        ["Judiciary", 6],
        ["Federalism", 7],
        ["Local Governments", 8],
      ]),
      S("History", "history", [
        ["From the Beginning of Time", 1],
        ["Writing and City Life", 2],
        ["An Empire Across Three Continents", 3],
        ["The Central Islamic Lands", 4],
        ["Nomadic Empires", 5],
        ["The Three Orders", 6],
        ["Changing Cultural Traditions", 7],
        ["Confrontation of Cultures", 8],
      ]),
      S("Geography", "geography", [
        ["Geography as a Discipline", 1],
        ["The Origin and Evolution of the Earth", 2],
        ["Interior of the Earth", 3],
        ["Distribution of Oceans and Continents", 4],
        ["Minerals and Rocks", 5],
        ["Geomorphic Processes", 6],
        ["Landforms and their Evolution", 7],
        ["Composition and Structure of Atmosphere", 8],
      ]),
      S("Sanskrit", "sanskrit", [
        ["स्वर्णकाकः", 1],
        ["सुधामन्थनम्", 2],
        ["व्यायोगः", 3],
        ["हितोपदेशः", 4],
        ["भारती वसन्तगाथा", 5],
      ]),
    ],
  },
  {
    name: "Class 12",
    slug: "class-12",
    subjects: [
      S("English Core", "english-core", [
        ["The Last Lesson", 1],
        ["Lost Spring", 2],
        ["Deep Water", 3],
        ["The Rattrap", 4],
        ["Indigo", 5],
        ["Poets and Pancakes", 6],
        ["The Interview", 7],
        ["Going Places", 8],
      ]),
      S("Mathematics", "mathematics", [
        ["Relations and Functions", 1],
        ["Inverse Trigonometric Functions", 2],
        ["Matrices", 3],
        ["Determinants", 4],
        ["Continuity and Differentiability", 5],
        ["Application of Derivatives", 6],
        ["Integrals", 7],
        ["Application of Integrals", 8],
        ["Differential Equations", 9],
        ["Vector Algebra", 10],
        ["Three Dimensional Geometry", 11],
        ["Linear Programming", 12],
        ["Probability", 13],
      ]),
      S("Physics", "physics", [
        ["Electric Charges and Fields", 1],
        ["Electrostatic Potential and Capacitance", 2],
        ["Current Electricity", 3],
        ["Moving Charges and Magnetism", 4],
        ["Magnetism and Matter", 5],
        ["Electromagnetic Induction", 6],
        ["Alternating Current", 7],
        ["Electromagnetic Waves", 8],
        ["Ray Optics and Optical Instruments", 9],
        ["Wave Optics", 10],
        ["Dual Nature of Radiation and Matter", 11],
        ["Atoms", 12],
        ["Nuclei", 13],
        ["Semiconductor Electronics", 14],
        ["Communication Systems", 15],
      ]),
      S("Chemistry", "chemistry", [
        ["The Solid State", 1],
        ["Solutions", 2],
        ["Electrochemistry", 3],
        ["Chemical Kinetics", 4],
        ["Surface Chemistry", 5],
        ["General Principles and Processes of Isolation of Elements", 6],
        ["The p-Block Elements", 7],
        ["The d- and f-Block Elements", 8],
        ["Coordination Compounds", 9],
        ["Haloalkanes and Haloarenes", 10],
        ["Alcohols, Phenols and Ethers", 11],
        ["Aldehydes, Ketones and Carboxylic Acids", 12],
        ["Amines", 13],
        ["Biomolecules", 14],
        ["Polymers", 15],
        ["Chemistry in Everyday Life", 16],
      ]),
      S("Biology", "biology", [
        ["Reproduction in Organisms", 1],
        ["Sexual Reproduction in Flowering Plants", 2],
        ["Human Reproduction", 3],
        ["Reproductive Health", 4],
        ["Principles of Inheritance and Variation", 5],
        ["Molecular Basis of Inheritance", 6],
        ["Evolution", 7],
        ["Human Health and Disease", 8],
        ["Strategies for Enhancement in Food Production", 9],
        ["Microbes in Human Welfare", 10],
        ["Biotechnology — Principles", 11],
        ["Biotechnology and its Applications", 12],
        ["Organisms and Populations", 13],
        ["Ecosystem", 14],
        ["Biodiversity and Conservation", 15],
        ["Environmental Issues", 16],
      ]),
      S("Computer Science", "computer-science", [
        ["Exception Handling", 1],
        ["File Handling", 2],
        ["Stacks and Queues", 3],
        ["Computer Networks", 4],
        ["Database Concepts", 5],
        ["Structured Query Language", 6],
        ["Interface Python with SQL", 7],
        ["Data Visualization", 8],
      ]),
      S("Accountancy", "accountancy", [
        ["Accounting for Not-for-Profit Organisation", 1],
        ["Accounting for Partnership", 2],
        ["Reconstitution of Partnership", 3],
        ["Dissolution of Partnership", 4],
        ["Accounting for Share Capital", 5],
        ["Issue and Redemption of Debentures", 6],
        ["Financial Statements of a Company", 7],
        ["Analysis of Financial Statements", 8],
      ]),
      S("Business Studies", "business-studies", [
        ["Nature and Significance of Management", 1],
        ["Principles of Management", 2],
        ["Business Environment", 3],
        ["Planning", 4],
        ["Organising", 5],
        ["Staffing", 6],
        ["Directing", 7],
        ["Controlling", 8],
        ["Financial Management", 9],
        ["Financial Markets", 10],
      ]),
      S("Economics", "economics", [
        ["Introduction to Macroeconomics", 1],
        ["National Income Accounting", 2],
        ["Money and Banking", 3],
        ["Income Determination", 4],
        ["Government Budget and the Economy", 5],
        ["Open Economy Macroeconomics", 6],
        ["Indian Economy 1950–1990", 7],
        ["Liberalisation, Privatisation and Globalisation", 8],
        ["Poverty and Human Capital", 9],
        ["Rural Development", 10],
        ["Employment and Infrastructure", 11],
        ["Sustainable Economic Development", 12],
      ]),
      S("Political Science", "political-science", [
        ["The Cold War Era", 1],
        ["The End of Bipolarity", 2],
        ["US Hegemony in World Politics", 3],
        ["Alternative Centres of Power", 4],
        ["Contemporary South Asia", 5],
        ["International Organisations", 6],
        ["Security in the Contemporary World", 7],
        ["Environment and Natural Resources", 8],
      ]),
      S("History", "history", [
        ["The Story of the First Cities", 1],
        ["Kings and Chronicles", 2],
        ["Colonialism and the Countryside", 3],
        ["Rebels and the Raj", 4],
        ["Colonial Cities", 5],
        ["Mahatma Gandhi and the Nationalist Movement", 6],
        ["Understanding Partition", 7],
        ["Framing the Constitution", 8],
      ]),
      S("Geography", "geography", [
        ["Human Geography", 1],
        ["The World Population", 2],
        ["Population Composition", 3],
        ["Human Development", 4],
        ["Primary Activities", 5],
        ["Secondary Activities", 6],
        ["Tertiary and Quaternary Activities", 7],
        ["Transport and Communication", 8],
        ["International Trade", 9],
        ["Geographical Perspective on Selected Issues", 10],
      ]),
      S("Sanskrit", "sanskrit", [
        ["सुधामन्थनम्", 1],
        ["भारती वसन्तगाथा", 2],
        ["श्रीहर्ष", 3],
        ["व्यायोगः", 4],
        ["मेघदूतम्", 5],
      ]),
    ],
  },
];
