import { initDb, getDb } from "../db";
import {
  users,
  students,
  courses,
  subjects,
  materials,
  activities,
  questions,
  announcements,
  files,
  adminProfiles,
} from "../db/schema";
import { hashPassword } from "../utils/password";
import { fileStorage } from "../utils/storage";
import { eq, sql } from "drizzle-orm";

const sampleText = (title: string) =>
  `GyaanSetu Sample Material\n\n${title}\n\nThis is a placeholder study resource generated by the seed script. Replace it with a real PDF / document when managing materials from the admin panel.\n`;

async function ensureAdmin(db: any) {
  const email = (process.env.SEED_ADMIN_EMAIL || "admin@gyaansetu.app").toLowerCase().trim();
  const [existing] = await db.select().from(users).where(eq(users.email, email)).limit(1);
  if (existing) {
    console.log(`✓ Admin already exists: ${email}`);
    return existing;
  }
  const password = process.env.SEED_ADMIN_PASSWORD || "Admin@123";
  const adminHash = await hashPassword(password);
  const [admin] = await db
    .insert(users)
    .values({ name: "GyaanSetu Admin", email, passwordHash: adminHash, role: "admin", status: "active" })
    .returning();
  await db
    .insert(adminProfiles)
    .values({ userId: admin.id, phone: "+910000000000", designation: "Administrator", bio: "Platform administrator" });
  console.log(`✓ Created admin: ${email} / ${password}`);
  return admin;
}

async function ensureDemoStudents(db: any, courseId: string) {
  const demoStudents = [
    { name: "Yashmaan Rao", code: "GS-2026-001", email: "yashmaan@gyaansetu.app", className: "10th", batch: "A" },
    { name: "Ananya Sharma", code: "GS-2026-002", email: "ananya@gyaansetu.app", className: "9th", batch: "A" },
    { name: "Rohan Mehta", code: "GS-2026-003", email: "rohan@gyaansetu.app", className: "11th", batch: "B" },
  ];
  for (const ds of demoStudents) {
    const [existing] = await db
      .select()
      .from(users)
      .where(eq(users.email, ds.email.toLowerCase()))
      .limit(1);
    if (existing) {
      console.log(`✓ Demo student already exists: ${ds.email}`);
      continue;
    }
    const hash = await hashPassword("Student@123");
    const [u] = await db
      .insert(users)
      .values({ name: ds.name, email: ds.email, passwordHash: hash, role: "student", status: "active" })
      .returning();
    await db.insert(students).values({
      userId: u.id,
      studentCode: ds.code,
      phone: "+91000000000" + ds.code.slice(-2),
      className: ds.className,
      courseId,
      batch: ds.batch,
      guardianName: "Guardian of " + ds.name,
      enrollmentDate: "2026-04-01",
    });
    console.log(`✓ Created demo student: ${ds.email} / Student@123 (class ${ds.className})`);
  }
}

async function ensureDefaultCourse(db: any) {
  const [existing] = await db.select().from(courses).limit(1);
  if (existing) return existing.id;
  const [course] = await db
    .insert(courses)
    .values({ name: "Class 10", code: "CL10", description: "Secondary level" })
    .returning();
  return course.id;
}

async function seedSampleContent(db: any, adminId: string, courseId: string) {
  const [{ m }] = await db.select({ m: sql<number>`count(*)::int` }).from(materials);
  if (Number(m) > 0) {
    console.log("✓ Sample content already exists — skipping sample content.");
    return;
  }

  const course = { id: courseId };
  const subjectNames = ["Mathematics", "Science", "English", "History", "Geography"];
  const subjIds: string[] = [];
  for (const name of subjectNames) {
    const [s] = await db
      .insert(subjects)
      .values({ name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), courseId: course.id, colorHex: "#4f46e5" })
      .returning();
    subjIds.push(s.id);
  }

  // Notes (10)
  for (let i = 1; i <= 10; i++) {
    const title = `Revision Notes ${i} — ${subjectNames[i % 5]}`;
    const meta = fileStorage.validateAndStore(Buffer.from(sampleText(title)), `notes-${i}.txt`, "text/plain");
    const [f] = await db
      .insert(files)
      .values({ originalName: meta.originalName, storedName: meta.storedName, mimeType: meta.mimeType, ext: meta.ext, sizeBytes: meta.sizeBytes, kind: meta.kind })
      .returning();
    await db.insert(materials).values({
      title,
      description: "Concise revision notes for quick study.",
      type: "note",
      subjectId: subjIds[i % 5],
      courseId: course.id,
      topic: `Chapter ${i}`,
      fileId: f.id,
      visibility: "all",
      status: "published",
      downloadAllowed: true,
      publishedAt: new Date(),
    });
  }

  // Books (5)
  const bookTitles = ["Foundations of Algebra", "Wonderful World of Science", "English Grammar Essentials", "The History of Civilizations", "Understanding Our Planet"];
  for (let i = 0; i < bookTitles.length; i++) {
    const title = bookTitles[i];
    const meta = fileStorage.validateAndStore(Buffer.from(sampleText(title)), `book-${i + 1}.txt`, "text/plain");
    const [f] = await db
      .insert(files)
      .values({ originalName: meta.originalName, storedName: meta.storedName, mimeType: meta.mimeType, ext: meta.ext, sizeBytes: meta.sizeBytes, kind: meta.kind })
      .returning();
    await db.insert(materials).values({
      title,
      description: "Reference textbook for the course.",
      type: "book",
      subjectId: subjIds[i],
      courseId: course.id,
      author: ["Dr. A. Kumar", "Prof. B. Singh", "C. Verma", "D. Iyer", "E. Nair"][i],
      fileId: f.id,
      visibility: "all",
      status: "published",
      downloadAllowed: true,
      publishedAt: new Date(),
    });
  }

  // Activities with MCQs (10 activities, 2 questions each = 20 questions)
  const today = new Date();
  const tomorrow = new Date(today); tomorrow.setDate(today.getDate() + 1);
  const yesterday = new Date(today); yesterday.setDate(today.getDate() - 1);

  const activityDefs = [
    { title: "Daily MCQ Challenge — Algebra", type: "mcq", date: today, isDaily: true, subject: 0 },
    { title: "Daily MCQ Challenge — Physics", type: "mcq", date: today, isDaily: true, subject: 1 },
    { title: "Weekly Quiz — English", type: "quiz", date: yesterday, isDaily: false, subject: 2 },
    { title: "History Reading Task", type: "reading", date: today, isDaily: false, subject: 3 },
    { title: "Geography Practice", type: "practice", date: tomorrow, isDaily: false, subject: 4 },
    { title: "Daily MCQ Challenge — Geometry", type: "mcq", date: yesterday, isDaily: true, subject: 0 },
    { title: "Science Quiz", type: "quiz", date: today, isDaily: false, subject: 1 },
    { title: "Daily Challenge — Biology", type: "challenge", date: tomorrow, isDaily: true, subject: 1 },
    { title: "English Assignment", type: "assignment", date: today, isDaily: false, subject: 2 },
    { title: "Mock Test — Mixed", type: "quiz", date: yesterday, isDaily: false, subject: 4 },
  ];

  let qIndex = 0;
  for (const def of activityDefs) {
    const totalMarks = 2;
    const [act] = await db
      .insert(activities)
      .values({
        title: def.title,
        description: "Attempt all questions and submit before the timer ends.",
        type: def.type,
        activityDate: def.date.toISOString().slice(0, 10),
        startTime: "08:00",
        endTime: "20:00",
        subjectId: subjIds[def.subject],
        courseId: course.id,
        timeLimitMinutes: 10,
        passingScore: 50,
        maxAttempts: 2,
        status: "published",
        isDaily: def.isDaily,
        totalMarks,
        createdBy: adminId,
      })
      .returning();
    for (let k = 0; k < 2; k++) {
      qIndex += 1;
      const opts = [
        { key: "a", text: `Option A for Q${qIndex}` },
        { key: "b", text: `Option B for Q${qIndex}` },
        { key: "c", text: `Option C for Q${qIndex}` },
        { key: "d", text: `Option D for Q${qIndex}` },
      ];
      await db.insert(questions).values({
        activityId: act.id,
        text: `Sample question ${qIndex} on ${subjectNames[def.subject]}?`,
        options: opts,
        correctKey: ["a", "b", "c", "d"][qIndex % 4],
        explanation: "Review the relevant chapter for the correct concept.",
        marks: 1,
        difficulty: ["easy", "medium", "hard"][qIndex % 3] as any,
        topic: `Topic ${qIndex}`,
        orderIndex: k,
      });
    }
  }

  // Announcements
  await db.insert(announcements).values([
    {
      title: "Welcome to GyaanSetu!",
      message: "Your learning portal is ready. Check today's MCQ challenge and start your streak.",
      priority: "important",
      publishDate: new Date(),
      targetRole: "all",
      createdBy: adminId,
    },
    {
      title: "New Books Added",
      message: "We added 5 new reference books to the library. Happy reading!",
      priority: "normal",
      publishDate: new Date(),
      targetRole: "students",
      createdBy: adminId,
    },
  ]);

  console.log("✓ Sample courses, materials, activities and announcements seeded.");
}

async function main() {
  await initDb();
  const db = getDb();

  const admin = await ensureAdmin(db);
  const courseId = await ensureDefaultCourse(db);

  await ensureDemoStudents(db, courseId);
  await seedSampleContent(db, admin.id, courseId);

  console.log("✓ Seed complete.");
  console.log(`Admin login: ${(process.env.SEED_ADMIN_EMAIL || "admin@gyaansetu.app")} / ${process.env.SEED_ADMIN_PASSWORD || "Admin@123"}`);
  console.log("Students: yashmaan@gyaansetu.app / Student@123 (etc.)");
}

main().catch((e) => {
  console.error("Seed failed:", e);
  process.exit(1);
});
